### ISSUE TITLE
提議：開始翻譯Rust標準庫(網頁)

### ISSUE THREAD

**Issue by 3442853561** [askeing/rust-book#37]

**Comment by askeing** [comment]
這裡翻譯的是 "The Rust Programming Language"，內容來自 Rust 專案中 `src/doc/book/` 的目錄。

Standard Library 的內容可能比較適合再開一個 repository 集中翻譯比較好？
你有什麼想法或建議嗎？

**Comment by 3442853561** [comment]
我的建議是做一個Rust(正體)中文社區，The Rust Programming Language可以是其中的一本電子書。更多的是關於Rust語言的中文問答
